apiVersion: v1
kind: Service
metadata:
  name: arangodb-service
spec:
  selector:
    app.kubernetes.io/name: arangodb
  ports:
    - protocol: TCP
      port: 8529
      targetPort: 8529  
  type: NodePort
