apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pn-ingress
  labels:
    owner: pn
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  pn-service-client
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  pn-service-server
                port:
                  number: 3000

